### ISSUE TITLE
Question: How to capture full traceback from resolver exceptions?

### ISSUE THREAD

**Issue by bkcsfi** [dailymotion/tartiflette#225]
When an exception is raised in a resolver, such as KeyError, the result is returned to the client as a TartifletteError/GraphQLError instance.  That's ok for the client but makes development and debugging difficult as the actual exception type is lost.

I know I can implement a global error coercer which could retain the actual type of the exception. However I'm still missing out on the traceback and context variables that I could see with e.g. cgitb, or logging.exception.

More specifically, I would like to capture all exceptions and send them to Sentry.  

To do this, I need access to exception context from sys.exc_info()

I've been poking around the code to see if I can find where, e.g. a resolver KeyError would get caught and then converted to TartifletteError.  I even tried subclassing Engine and adding a try/except to execute(), but that didn't work.  

At this point my only option is to add another decorator to all my resolvers to catch any exceptions. I'd rather not do that.

Can you please suggest where in the code, if at all possible,  I could catch low-level exception details? 

Thanks

**Comment by bkcsfi** [comment]
ah, so its resolver/factory.py that's doing the catch.. hmm. looks like I'll have to write  a decorator for every resolver.

**Comment by abusi** [comment]
@bkcsfi I think @Maximilien-R has an easier solution for you here. I'm assigning this issue to him. I let him give the details to you.

**Comment by Maximilien-R** [comment]
Hi @bkcsfi,

In my opinion, for your use case, the easiest way to log exception wrapped into a `TartifletteError` is to use the `error_coercer` feature (cf. https://tartiflette.io/docs/api/error-handling#advanced-add-a-global-error-coercer).

You could have something like that:
```python
import logging

from typing import Any, Dict, Union

from tartiflette import Engine

logger = logging.getLogger(__name__)


def logger_error_coercer(
    exception: Union["TartifletteError", Exception], error: Dict[str, Any]
) -> Dict[str, Any]:
    original_error = getattr(exception, "original_error", None)
    if original_error is not None:
        logger.error(original_error, exc_info=original_error)
    return error


engine = Engine(
    "your-sdl.graphql",
    error_coercer=logger_error_coercer,
)
```

FYI, Tartiflette catch every exceptions which occurs [during the resolving process](https://github.com/dailymotion/tartiflette/blob/master/tartiflette/parser/nodes/field.py#L188-L198). If an exception isn't coercible (it doesn't implement a `coerce_value` method) it will be wrap into a `GraphQLError` but the original exception will be [set to the](https://github.com/dailymotion/tartiflette/blob/master/tartiflette/parser/nodes/field.py#L218-L224) `original_error` attribute. I think this part isn't documented yet but it should come soon :)


I hope this solution will meet your needs. Otherwise, do not hesitate to come back to me.

**Comment by Maximilien-R** [comment]
The value set to the `original_error` attribute is the exception that is returned [here](https://github.com/dailymotion/tartiflette/blob/master/tartiflette/resolver/factory.py#L104) which occurs during the resolving process. Meaning that it should contains the full original exception information including its traceback.

Regarding the fact that on my proposed code, `exc_info` parameter is the original exception, its not a problem since according to the [documentation](https://docs.python.org/3/library/logging.html#logging.Logger.debug), this paremeter can be an exception instance (and in this case, the exception data are used instead of `sys.exc_info()`):
> There are three keyword arguments in kwargs which are inspected: exc_info, stack_info, and extra.

> If exc_info does not evaluate as false, it causes exception information to be added to the logging message. If an exception tuple (in the format returned by sys.exc_info()) or an exception instance is provided, it is used; otherwise, sys.exc_info() is called to get the exception information.

Also, I just tested my solution on the `dogs` example from the `tartiflette-aiohttp` project. If you want, you can try it yourself by applying the attached patch file to it:
```
git clone https://github.com/dailymotion/tartiflette-aiohttp.git
patch -p1 < logger-error-coercer-patch.txt
cd examples/aiohttp/dogs
make run
```

Open the [GraphiQL](http://localhost:8090/graphiql) client and run the `Dog` operation. You should have something like:
![logger-error](https://user-images.githubusercontent.com/6966240/57512938-53d8d880-730d-11e9-9716-9817f61853f7.png)

[logger-error-coercer-patch.txt](https://github.com/dailymotion/tartiflette/files/3165547/logger-error-coercer-patch.txt)

**Comment by bkcsfi** [comment]
Thanks so much for your assistance with this issue. 

What threw me off on this is that sys.exc_info docs suggest it only works properly if its called from  within an except clause. 

However your sample code does work. Below is what I implemented, passing exceptions to sentry, or if that's not configured using logging.exception (I could also use cgitb here to get context vars).


```python
def logger_error_coercer(exception, error=None):
    original_error = getattr(exception, "original_error", None)
    if original_error is not None:
        if not sentry_sdk.capture_exception(original_error):
            logging.exception(
                "resolver error", exc_info=original_error, stack_info=True
            )
    return error
```
Sentry does in fact capture context variables on the stack as shown below

![image](https://user-images.githubusercontent.com/6412502/57538778-1da05680-7317-11e9-9347-ebb1a3766ace.png)
